// <auto-generated />
using System;
using Air_3550.Repo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(AirContext))]
    [Migration("20210425185330_CancellationAndCost")]
    partial class CancellationAndCost
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Air_3550.Models.Airport", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AirportCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AirportId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Elevation")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("Decimal(8,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("Decimal(9,6)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AirportId");

                    b.HasIndex("AirportId1");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            AirportId = 1,
                            AirportCode = "CLE",
                            City = "Cleveland",
                            Country = "USA",
                            Elevation = 791,
                            Latitude = 41.411667m,
                            Longitude = -81.849722m,
                            State = "Ohio"
                        },
                        new
                        {
                            AirportId = 2,
                            AirportCode = "ATL",
                            City = "Atlanta",
                            Country = "USA",
                            Elevation = 1027,
                            Latitude = 33.636667m,
                            Longitude = -84.428056m,
                            State = "Georgia"
                        },
                        new
                        {
                            AirportId = 3,
                            AirportCode = "LAX",
                            City = "Los Angeles",
                            Country = "USA",
                            Elevation = 125,
                            Latitude = 33.9425m,
                            Longitude = -118.408056m,
                            State = "California"
                        },
                        new
                        {
                            AirportId = 4,
                            AirportCode = "MDW",
                            City = "Chicago",
                            Country = "USA",
                            Elevation = 620,
                            Latitude = 41.786111m,
                            Longitude = -87.7525m,
                            State = "Illinois"
                        },
                        new
                        {
                            AirportId = 5,
                            AirportCode = "DAL",
                            City = "Dallas",
                            Country = "USA",
                            Elevation = 486,
                            Latitude = 32.847222m,
                            Longitude = -96.851667m,
                            State = "Texas"
                        },
                        new
                        {
                            AirportId = 6,
                            AirportCode = "DEN",
                            City = "Denver",
                            Country = "USA",
                            Elevation = 5430,
                            Latitude = 39.861667m,
                            Longitude = -104.673056m,
                            State = "Colorado"
                        },
                        new
                        {
                            AirportId = 7,
                            AirportCode = "LGA",
                            City = "New York",
                            Country = "USA",
                            Elevation = 19,
                            Latitude = 40.775m,
                            Longitude = -73.875m,
                            State = "New York"
                        },
                        new
                        {
                            AirportId = 8,
                            AirportCode = "MIA",
                            City = "Miami",
                            Country = "USA",
                            Elevation = 9,
                            Latitude = 25.793333m,
                            Longitude = -80.290556m,
                            State = "Florida"
                        },
                        new
                        {
                            AirportId = 9,
                            AirportCode = "SEA",
                            City = "Seattle",
                            Country = "USA",
                            Elevation = 433,
                            Latitude = 47.448889m,
                            Longitude = -122.309444m,
                            State = "Washington"
                        },
                        new
                        {
                            AirportId = 10,
                            AirportCode = "BNA",
                            City = "Nashville",
                            Country = "USA",
                            Elevation = 599,
                            Latitude = 36.126667m,
                            Longitude = -86.681944m,
                            State = "Tennessee"
                        });
                });

            modelBuilder.Entity("Air_3550.Models.CustomerInfo", b =>
                {
                    b.Property<int>("CustomerInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditBalance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreditCardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PointsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerInfoId");

                    b.ToTable("CustomerInfo");
                });

            modelBuilder.Entity("Air_3550.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DestinationAirportId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OriginAirportId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlaneTypePlaneId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isCanceled")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlightId");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("OriginAirportId");

                    b.HasIndex("PlaneTypePlaneId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            DepartureTime = new TimeSpan(0, 6, 10, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 1,
                            OriginAirportId = 9,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 121,
                            DepartureTime = new TimeSpan(0, 7, 20, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 121,
                            OriginAirportId = 9,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 122,
                            DepartureTime = new TimeSpan(0, 8, 10, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 122,
                            OriginAirportId = 9,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 2,
                            DepartureTime = new TimeSpan(0, 9, 35, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 2,
                            OriginAirportId = 9,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 123,
                            DepartureTime = new TimeSpan(0, 10, 15, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 123,
                            OriginAirportId = 9,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 124,
                            DepartureTime = new TimeSpan(0, 11, 40, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 124,
                            OriginAirportId = 9,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 125,
                            DepartureTime = new TimeSpan(0, 12, 10, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 125,
                            OriginAirportId = 9,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 3,
                            DepartureTime = new TimeSpan(0, 14, 10, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 3,
                            OriginAirportId = 9,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 4,
                            DepartureTime = new TimeSpan(0, 18, 35, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 4,
                            OriginAirportId = 9,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 5,
                            DepartureTime = new TimeSpan(0, 6, 50, 0, 0),
                            DestinationAirportId = 9,
                            FlightNumber = 5,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 6,
                            DepartureTime = new TimeSpan(0, 9, 30, 0, 0),
                            DestinationAirportId = 9,
                            FlightNumber = 6,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 7,
                            DepartureTime = new TimeSpan(0, 15, 55, 0, 0),
                            DestinationAirportId = 9,
                            FlightNumber = 7,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 8,
                            DepartureTime = new TimeSpan(0, 20, 55, 0, 0),
                            DestinationAirportId = 9,
                            FlightNumber = 8,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 9,
                            DepartureTime = new TimeSpan(0, 6, 5, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 9,
                            OriginAirportId = 3,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 10,
                            DepartureTime = new TimeSpan(0, 11, 55, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 10,
                            OriginAirportId = 3,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 11,
                            DepartureTime = new TimeSpan(0, 14, 25, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 11,
                            OriginAirportId = 3,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 12,
                            DepartureTime = new TimeSpan(0, 17, 55, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 12,
                            OriginAirportId = 3,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 13,
                            DepartureTime = new TimeSpan(0, 8, 0, 0, 0),
                            DestinationAirportId = 3,
                            FlightNumber = 13,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 14,
                            DepartureTime = new TimeSpan(0, 12, 55, 0, 0),
                            DestinationAirportId = 3,
                            FlightNumber = 14,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 15,
                            DepartureTime = new TimeSpan(0, 17, 0, 0, 0),
                            DestinationAirportId = 3,
                            FlightNumber = 15,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 16,
                            DepartureTime = new TimeSpan(0, 20, 35, 0, 0),
                            DestinationAirportId = 3,
                            FlightNumber = 16,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 17,
                            DepartureTime = new TimeSpan(0, 6, 10, 0, 0),
                            DestinationAirportId = 5,
                            FlightNumber = 17,
                            OriginAirportId = 3,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 18,
                            DepartureTime = new TimeSpan(0, 11, 40, 0, 0),
                            DestinationAirportId = 5,
                            FlightNumber = 18,
                            OriginAirportId = 3,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 19,
                            DepartureTime = new TimeSpan(0, 14, 50, 0, 0),
                            DestinationAirportId = 5,
                            FlightNumber = 19,
                            OriginAirportId = 3,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 20,
                            DepartureTime = new TimeSpan(0, 18, 10, 0, 0),
                            DestinationAirportId = 5,
                            FlightNumber = 20,
                            OriginAirportId = 3,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 21,
                            DepartureTime = new TimeSpan(0, 7, 30, 0, 0),
                            DestinationAirportId = 3,
                            FlightNumber = 21,
                            OriginAirportId = 5,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 22,
                            DepartureTime = new TimeSpan(0, 9, 45, 0, 0),
                            DestinationAirportId = 3,
                            FlightNumber = 22,
                            OriginAirportId = 5,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 23,
                            DepartureTime = new TimeSpan(0, 14, 10, 0, 0),
                            DestinationAirportId = 3,
                            FlightNumber = 23,
                            OriginAirportId = 5,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 24,
                            DepartureTime = new TimeSpan(0, 20, 50, 0, 0),
                            DestinationAirportId = 3,
                            FlightNumber = 24,
                            OriginAirportId = 5,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 25,
                            DepartureTime = new TimeSpan(0, 7, 10, 0, 0),
                            DestinationAirportId = 5,
                            FlightNumber = 25,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 26,
                            DepartureTime = new TimeSpan(0, 9, 40, 0, 0),
                            DestinationAirportId = 5,
                            FlightNumber = 26,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 27,
                            DepartureTime = new TimeSpan(0, 14, 5, 0, 0),
                            DestinationAirportId = 5,
                            FlightNumber = 27,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 28,
                            DepartureTime = new TimeSpan(0, 18, 55, 0, 0),
                            DestinationAirportId = 5,
                            FlightNumber = 28,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 29,
                            DepartureTime = new TimeSpan(0, 7, 10, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 29,
                            OriginAirportId = 5,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 30,
                            DepartureTime = new TimeSpan(0, 11, 10, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 30,
                            OriginAirportId = 5,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 31,
                            DepartureTime = new TimeSpan(0, 16, 45, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 31,
                            OriginAirportId = 5,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 32,
                            DepartureTime = new TimeSpan(0, 20, 55, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 32,
                            OriginAirportId = 5,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 33,
                            DepartureTime = new TimeSpan(0, 8, 25, 0, 0),
                            DestinationAirportId = 4,
                            FlightNumber = 33,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 34,
                            DepartureTime = new TimeSpan(0, 10, 55, 0, 0),
                            DestinationAirportId = 4,
                            FlightNumber = 34,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 35,
                            DepartureTime = new TimeSpan(0, 13, 5, 0, 0),
                            DestinationAirportId = 4,
                            FlightNumber = 35,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 36,
                            DepartureTime = new TimeSpan(0, 18, 50, 0, 0),
                            DestinationAirportId = 4,
                            FlightNumber = 36,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 37,
                            DepartureTime = new TimeSpan(0, 6, 50, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 37,
                            OriginAirportId = 4,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 38,
                            DepartureTime = new TimeSpan(0, 10, 30, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 38,
                            OriginAirportId = 4,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 39,
                            DepartureTime = new TimeSpan(0, 12, 45, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 39,
                            OriginAirportId = 4,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 40,
                            DepartureTime = new TimeSpan(0, 16, 45, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 40,
                            OriginAirportId = 4,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 41,
                            DepartureTime = new TimeSpan(0, 6, 45, 0, 0),
                            DestinationAirportId = 10,
                            FlightNumber = 41,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 42,
                            DepartureTime = new TimeSpan(0, 9, 15, 0, 0),
                            DestinationAirportId = 10,
                            FlightNumber = 42,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 43,
                            DepartureTime = new TimeSpan(0, 15, 20, 0, 0),
                            DestinationAirportId = 10,
                            FlightNumber = 43,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 44,
                            DepartureTime = new TimeSpan(0, 18, 50, 0, 0),
                            DestinationAirportId = 10,
                            FlightNumber = 44,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 45,
                            DepartureTime = new TimeSpan(0, 6, 40, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 45,
                            OriginAirportId = 10,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 46,
                            DepartureTime = new TimeSpan(0, 9, 5, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 46,
                            OriginAirportId = 10,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 47,
                            DepartureTime = new TimeSpan(0, 15, 30, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 47,
                            OriginAirportId = 10,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 48,
                            DepartureTime = new TimeSpan(0, 17, 50, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 48,
                            OriginAirportId = 10,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 49,
                            DepartureTime = new TimeSpan(0, 7, 0, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 49,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 126,
                            DepartureTime = new TimeSpan(0, 8, 10, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 126,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 50,
                            DepartureTime = new TimeSpan(0, 9, 15, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 50,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 127,
                            DepartureTime = new TimeSpan(0, 10, 30, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 127,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 128,
                            DepartureTime = new TimeSpan(0, 11, 20, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 128,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 129,
                            DepartureTime = new TimeSpan(0, 12, 10, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 129,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 51,
                            DepartureTime = new TimeSpan(0, 14, 30, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 51,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 52,
                            DepartureTime = new TimeSpan(0, 18, 40, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 52,
                            OriginAirportId = 6,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 53,
                            DepartureTime = new TimeSpan(0, 7, 20, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 53,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 54,
                            DepartureTime = new TimeSpan(0, 11, 10, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 54,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 55,
                            DepartureTime = new TimeSpan(0, 14, 40, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 55,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 56,
                            DepartureTime = new TimeSpan(0, 18, 20, 0, 0),
                            DestinationAirportId = 6,
                            FlightNumber = 56,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 57,
                            DepartureTime = new TimeSpan(0, 7, 10, 0, 0),
                            DestinationAirportId = 1,
                            FlightNumber = 57,
                            OriginAirportId = 4,
                            PlaneTypePlaneId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 58,
                            DepartureTime = new TimeSpan(0, 9, 40, 0, 0),
                            DestinationAirportId = 1,
                            FlightNumber = 58,
                            OriginAirportId = 4,
                            PlaneTypePlaneId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 59,
                            DepartureTime = new TimeSpan(0, 12, 45, 0, 0),
                            DestinationAirportId = 1,
                            FlightNumber = 59,
                            OriginAirportId = 4,
                            PlaneTypePlaneId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 60,
                            DepartureTime = new TimeSpan(0, 16, 30, 0, 0),
                            DestinationAirportId = 1,
                            FlightNumber = 60,
                            OriginAirportId = 4,
                            PlaneTypePlaneId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 61,
                            DepartureTime = new TimeSpan(0, 7, 0, 0, 0),
                            DestinationAirportId = 4,
                            FlightNumber = 61,
                            OriginAirportId = 1,
                            PlaneTypePlaneId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 62,
                            DepartureTime = new TimeSpan(0, 10, 10, 0, 0),
                            DestinationAirportId = 4,
                            FlightNumber = 62,
                            OriginAirportId = 1,
                            PlaneTypePlaneId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 63,
                            DepartureTime = new TimeSpan(0, 15, 35, 0, 0),
                            DestinationAirportId = 4,
                            FlightNumber = 63,
                            OriginAirportId = 1,
                            PlaneTypePlaneId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 64,
                            DepartureTime = new TimeSpan(0, 19, 20, 0, 0),
                            DestinationAirportId = 4,
                            FlightNumber = 64,
                            OriginAirportId = 1,
                            PlaneTypePlaneId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 65,
                            DepartureTime = new TimeSpan(0, 9, 0, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 65,
                            OriginAirportId = 4,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 66,
                            DepartureTime = new TimeSpan(0, 11, 10, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 66,
                            OriginAirportId = 4,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 67,
                            DepartureTime = new TimeSpan(0, 13, 40, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 67,
                            OriginAirportId = 4,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 68,
                            DepartureTime = new TimeSpan(0, 17, 35, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 68,
                            OriginAirportId = 4,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 69,
                            DepartureTime = new TimeSpan(0, 6, 40, 0, 0),
                            DestinationAirportId = 4,
                            FlightNumber = 69,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 70,
                            DepartureTime = new TimeSpan(0, 9, 35, 0, 0),
                            DestinationAirportId = 4,
                            FlightNumber = 70,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 71,
                            DepartureTime = new TimeSpan(0, 12, 10, 0, 0),
                            DestinationAirportId = 4,
                            FlightNumber = 71,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 72,
                            DepartureTime = new TimeSpan(0, 18, 25, 0, 0),
                            DestinationAirportId = 4,
                            FlightNumber = 72,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 73,
                            DepartureTime = new TimeSpan(0, 8, 45, 0, 0),
                            DestinationAirportId = 1,
                            FlightNumber = 73,
                            OriginAirportId = 10,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 74,
                            DepartureTime = new TimeSpan(0, 11, 10, 0, 0),
                            DestinationAirportId = 1,
                            FlightNumber = 74,
                            OriginAirportId = 10,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 75,
                            DepartureTime = new TimeSpan(0, 14, 30, 0, 0),
                            DestinationAirportId = 1,
                            FlightNumber = 75,
                            OriginAirportId = 10,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 76,
                            DepartureTime = new TimeSpan(0, 18, 20, 0, 0),
                            DestinationAirportId = 1,
                            FlightNumber = 76,
                            OriginAirportId = 10,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 77,
                            DepartureTime = new TimeSpan(0, 7, 10, 0, 0),
                            DestinationAirportId = 10,
                            FlightNumber = 77,
                            OriginAirportId = 1,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 78,
                            DepartureTime = new TimeSpan(0, 9, 50, 0, 0),
                            DestinationAirportId = 10,
                            FlightNumber = 78,
                            OriginAirportId = 1,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 79,
                            DepartureTime = new TimeSpan(0, 15, 20, 0, 0),
                            DestinationAirportId = 10,
                            FlightNumber = 79,
                            OriginAirportId = 1,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 80,
                            DepartureTime = new TimeSpan(0, 19, 20, 0, 0),
                            DestinationAirportId = 10,
                            FlightNumber = 80,
                            OriginAirportId = 1,
                            PlaneTypePlaneId = 1,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 81,
                            DepartureTime = new TimeSpan(0, 8, 10, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 81,
                            OriginAirportId = 10,
                            PlaneTypePlaneId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 82,
                            DepartureTime = new TimeSpan(0, 10, 40, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 82,
                            OriginAirportId = 10,
                            PlaneTypePlaneId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 83,
                            DepartureTime = new TimeSpan(0, 14, 35, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 83,
                            OriginAirportId = 10,
                            PlaneTypePlaneId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 84,
                            DepartureTime = new TimeSpan(0, 17, 40, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 84,
                            OriginAirportId = 10,
                            PlaneTypePlaneId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 85,
                            DepartureTime = new TimeSpan(0, 8, 20, 0, 0),
                            DestinationAirportId = 10,
                            FlightNumber = 85,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 86,
                            DepartureTime = new TimeSpan(0, 9, 50, 0, 0),
                            DestinationAirportId = 10,
                            FlightNumber = 86,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 87,
                            DepartureTime = new TimeSpan(0, 15, 20, 0, 0),
                            DestinationAirportId = 10,
                            FlightNumber = 87,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 88,
                            DepartureTime = new TimeSpan(0, 20, 10, 0, 0),
                            DestinationAirportId = 10,
                            FlightNumber = 88,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 3,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 89,
                            DepartureTime = new TimeSpan(0, 8, 0, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 89,
                            OriginAirportId = 1,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 90,
                            DepartureTime = new TimeSpan(0, 9, 45, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 90,
                            OriginAirportId = 1,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 91,
                            DepartureTime = new TimeSpan(0, 13, 40, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 91,
                            OriginAirportId = 1,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 92,
                            DepartureTime = new TimeSpan(0, 19, 0, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 92,
                            OriginAirportId = 1,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 93,
                            DepartureTime = new TimeSpan(0, 8, 5, 0, 0),
                            DestinationAirportId = 1,
                            FlightNumber = 93,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 94,
                            DepartureTime = new TimeSpan(0, 11, 10, 0, 0),
                            DestinationAirportId = 1,
                            FlightNumber = 94,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 95,
                            DepartureTime = new TimeSpan(0, 14, 5, 0, 0),
                            DestinationAirportId = 1,
                            FlightNumber = 95,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 96,
                            DepartureTime = new TimeSpan(0, 18, 30, 0, 0),
                            DestinationAirportId = 1,
                            FlightNumber = 96,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 97,
                            DepartureTime = new TimeSpan(0, 9, 0, 0, 0),
                            DestinationAirportId = 7,
                            FlightNumber = 97,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 130,
                            DepartureTime = new TimeSpan(0, 10, 20, 0, 0),
                            DestinationAirportId = 7,
                            FlightNumber = 130,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 98,
                            DepartureTime = new TimeSpan(0, 11, 10, 0, 0),
                            DestinationAirportId = 7,
                            FlightNumber = 98,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 131,
                            DepartureTime = new TimeSpan(0, 12, 30, 0, 0),
                            DestinationAirportId = 7,
                            FlightNumber = 131,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 99,
                            DepartureTime = new TimeSpan(0, 13, 50, 0, 0),
                            DestinationAirportId = 7,
                            FlightNumber = 99,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 100,
                            DepartureTime = new TimeSpan(0, 16, 40, 0, 0),
                            DestinationAirportId = 7,
                            FlightNumber = 100,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 101,
                            DepartureTime = new TimeSpan(0, 9, 30, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 101,
                            OriginAirportId = 7,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 102,
                            DepartureTime = new TimeSpan(0, 11, 30, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 102,
                            OriginAirportId = 7,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 103,
                            DepartureTime = new TimeSpan(0, 14, 0, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 103,
                            OriginAirportId = 7,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 104,
                            DepartureTime = new TimeSpan(0, 17, 10, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 104,
                            OriginAirportId = 7,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 105,
                            DepartureTime = new TimeSpan(0, 9, 10, 0, 0),
                            DestinationAirportId = 8,
                            FlightNumber = 105,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 106,
                            DepartureTime = new TimeSpan(0, 10, 40, 0, 0),
                            DestinationAirportId = 8,
                            FlightNumber = 106,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 107,
                            DepartureTime = new TimeSpan(0, 13, 45, 0, 0),
                            DestinationAirportId = 8,
                            FlightNumber = 107,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 108,
                            DepartureTime = new TimeSpan(0, 18, 40, 0, 0),
                            DestinationAirportId = 8,
                            FlightNumber = 108,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 109,
                            DepartureTime = new TimeSpan(0, 9, 30, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 109,
                            OriginAirportId = 8,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 110,
                            DepartureTime = new TimeSpan(0, 11, 20, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 110,
                            OriginAirportId = 8,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 111,
                            DepartureTime = new TimeSpan(0, 13, 45, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 111,
                            OriginAirportId = 8,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 112,
                            DepartureTime = new TimeSpan(0, 17, 10, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 112,
                            OriginAirportId = 8,
                            PlaneTypePlaneId = 4,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 113,
                            DepartureTime = new TimeSpan(0, 7, 45, 0, 0),
                            DestinationAirportId = 5,
                            FlightNumber = 113,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 114,
                            DepartureTime = new TimeSpan(0, 9, 20, 0, 0),
                            DestinationAirportId = 5,
                            FlightNumber = 114,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 115,
                            DepartureTime = new TimeSpan(0, 13, 10, 0, 0),
                            DestinationAirportId = 5,
                            FlightNumber = 115,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 116,
                            DepartureTime = new TimeSpan(0, 17, 20, 0, 0),
                            DestinationAirportId = 5,
                            FlightNumber = 116,
                            OriginAirportId = 2,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 117,
                            DepartureTime = new TimeSpan(0, 8, 10, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 117,
                            OriginAirportId = 5,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 118,
                            DepartureTime = new TimeSpan(0, 10, 15, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 118,
                            OriginAirportId = 5,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 119,
                            DepartureTime = new TimeSpan(0, 14, 45, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 119,
                            OriginAirportId = 5,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        },
                        new
                        {
                            FlightId = 120,
                            DepartureTime = new TimeSpan(0, 18, 20, 0, 0),
                            DestinationAirportId = 2,
                            FlightNumber = 120,
                            OriginAirportId = 5,
                            PlaneTypePlaneId = 2,
                            isCanceled = false
                        });
                });

            modelBuilder.Entity("Air_3550.Models.Plane", b =>
                {
                    b.Property<int>("PlaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlaneId");

                    b.ToTable("Planes");

                    b.HasData(
                        new
                        {
                            PlaneId = 1,
                            MaxSeats = 230,
                            Model = "Boeing 737 MAX"
                        },
                        new
                        {
                            PlaneId = 2,
                            MaxSeats = 416,
                            Model = "Boeing 747"
                        },
                        new
                        {
                            PlaneId = 3,
                            MaxSeats = 199,
                            Model = "Boeing 757"
                        },
                        new
                        {
                            PlaneId = 4,
                            MaxSeats = 550,
                            Model = "Boeing 777"
                        });
                });

            modelBuilder.Entity("Air_3550.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlightScheduledFlightId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TripId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isCanceled")
                        .HasColumnType("INTEGER");

                    b.HasKey("TicketId");

                    b.HasIndex("FlightScheduledFlightId");

                    b.HasIndex("TripId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Air_3550.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinationAirportId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OriginAirportId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isCanceled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totalCost")
                        .HasColumnType("INTEGER");

                    b.HasKey("TripId");

                    b.HasIndex("CustomerInfoId");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("OriginAirportId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Air_3550.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustInfoCustomerInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashedPass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserRole")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.HasIndex("CustInfoCustomerInfoId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            HashedPass = "360caebd9edb68609c0933bade3565350e59e284cc503ce61bf0eebd42fb7e5bd657a71ed1498225168757e7f1095920411cce27779e0c778ec52535deae2040",
                            LoginId = "marketing_manager",
                            UserRole = 1
                        },
                        new
                        {
                            UserId = 2,
                            HashedPass = "41ec260efa3aa054a91cc6cf9441e3652637f75946c8fa6c2e926f289e095f46e62e19a28e02fb0fc25dd047b1f04e6e03cf930d464b540c40c0045eb6b7e252",
                            LoginId = "load_engineer",
                            UserRole = 2
                        },
                        new
                        {
                            UserId = 3,
                            HashedPass = "ab8f196b4521a3aba1de420fe6ef552ce406d8551c3aef370f909cea85abbc77ca1d698ef31f659097eee16e365975047ff403df1aae6cc7ef54595c3ae4d172",
                            LoginId = "accounting_manager",
                            UserRole = 3
                        },
                        new
                        {
                            UserId = 4,
                            HashedPass = "e2289f3f3a66a81f5ffb52dff1a09cd2ae91a39eb248230d2907084679c6bacdb4a880da7835ca72003d8c37e107cf91c5f9795678303754eba1be42039bff4d",
                            LoginId = "flight_manager",
                            UserRole = 4
                        });
                });

            modelBuilder.Entity("Database.Models.ScheduledFlight", b =>
                {
                    b.Property<int>("ScheduledFlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketsPurchased")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScheduledFlightId");

                    b.HasIndex("FlightId");

                    b.ToTable("ScheduledFlights");
                });

            modelBuilder.Entity("Air_3550.Models.Airport", b =>
                {
                    b.HasOne("Air_3550.Models.Airport", null)
                        .WithMany("ConnectedAirports")
                        .HasForeignKey("AirportId1");
                });

            modelBuilder.Entity("Air_3550.Models.Flight", b =>
                {
                    b.HasOne("Air_3550.Models.Airport", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationAirportId");

                    b.HasOne("Air_3550.Models.Airport", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginAirportId");

                    b.HasOne("Air_3550.Models.Plane", "PlaneType")
                        .WithMany()
                        .HasForeignKey("PlaneTypePlaneId");

                    b.Navigation("Destination");

                    b.Navigation("Origin");

                    b.Navigation("PlaneType");
                });

            modelBuilder.Entity("Air_3550.Models.Ticket", b =>
                {
                    b.HasOne("Database.Models.ScheduledFlight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightScheduledFlightId");

                    b.HasOne("Air_3550.Models.Trip", null)
                        .WithMany("Tickets")
                        .HasForeignKey("TripId");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Air_3550.Models.Trip", b =>
                {
                    b.HasOne("Air_3550.Models.CustomerInfo", null)
                        .WithMany("Trips")
                        .HasForeignKey("CustomerInfoId");

                    b.HasOne("Air_3550.Models.Airport", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationAirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Air_3550.Models.Airport", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginAirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("Air_3550.Models.User", b =>
                {
                    b.HasOne("Air_3550.Models.CustomerInfo", "CustInfo")
                        .WithMany()
                        .HasForeignKey("CustInfoCustomerInfoId");

                    b.Navigation("CustInfo");
                });

            modelBuilder.Entity("Database.Models.ScheduledFlight", b =>
                {
                    b.HasOne("Air_3550.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Air_3550.Models.Airport", b =>
                {
                    b.Navigation("ConnectedAirports");
                });

            modelBuilder.Entity("Air_3550.Models.CustomerInfo", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Air_3550.Models.Trip", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
